/*
 * generated by Xtext 2.24.0
 */
package org.palladiosimulator.dataflow.confidentiality.pcm.dddsl.ide;


/**
 * Use this class to register ide components.
 */
public class DDDslIdeModule extends AbstractDDDslIdeModule {
}
