/*
 * generated by Xtext 2.24.0
 */
package org.palladiosimulator.dataflow.confidentiality.pcm.dddsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.palladiosimulator.dataflow.confidentiality.pcm.dddsl.DDDslRuntimeModule;
import org.palladiosimulator.dataflow.confidentiality.pcm.dddsl.DDDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DDDslIdeSetup extends DDDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DDDslRuntimeModule(), new DDDslIdeModule()));
	}
	
}
