/*
 * generated by Xtext 2.24.0
 */
package org.palladiosimulator.dataflow.confidentiality.pcm.dddsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.palladiosimulator.dataflow.confidentiality.pcm.model.confidentiality.ConfidentialityVariableCharacterisation
import org.palladiosimulator.dataflow.confidentiality.pcm.model.confidentiality.dictionary.PCMDataDictionary
import org.palladiosimulator.dataflow.confidentiality.pcm.model.confidentiality.expression.LhsEnumCharacteristicReference

import static org.hamcrest.CoreMatchers.*
import static org.hamcrest.MatcherAssert.*
import static org.junit.jupiter.api.Assertions.*

@ExtendWith(InjectionExtension)
@InjectWith(DDDslInjectorProvider)
class DDDslParsingTest {

	@Inject
	ParseHelper<PCMDataDictionary> parseHelper

	@Test
	def void loadModel() {
		val result = '''
			dictionary id "123"
		'''.parse
		assertThat(result.id, is("123"))
	}

	@Test
	def void testEnumCharacteristicReferences() {
		val result = '''
			dictionary id "_sgA9QPBCEeufp9jGDRJpXA"
			
			enum Roles {
				User
				Airline
			}
			enumCharacteristicType AssignedRoles using Roles
			enumCharacteristicType ReadAccess using Roles
			
			behavior foo {
				input ccd
				output RESULT
				RESULT.{
					*.* := ccd.*.*
					ReadAccess.Airline := true
				}
			
			}
		'''.parse
		var characterisations = result.reusableBehaviours.get(0).variableUsages.get(0).
			variableCharacterisation_VariableUsage;
		var characterisation = characterisations.get(1) as ConfidentialityVariableCharacterisation
		var lhs = characterisation.lhs as LhsEnumCharacteristicReference
		assertNotNull(lhs.characteristicType)
		assertNotNull(lhs.characteristicType.name)
		assertNotNull(lhs.literal)
		assertNotNull(lhs.literal.name)
	}

	protected def parse(CharSequence text) {
		val result = parseHelper.parse(text)
		assertNotNull(result)
		val errors = result.eResource.errors
		assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		result
	}
}
