/*
 * generated by Xtext 2.24.0
 */
package org.palladiosimulator.dataflow.confidentiality.pcm.dddsl;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.parsetree.reconstr.ITransientValueService;
import org.eclipse.xtext.resource.DerivedStateAwareResource;
import org.eclipse.xtext.resource.DerivedStateAwareResourceDescriptionManager;
import org.eclipse.xtext.resource.IDerivedStateComputer;
import org.eclipse.xtext.resource.IResourceDescription;
import org.eclipse.xtext.resource.XtextResource;
import org.palladiosimulator.dataflow.confidentiality.pcm.dddsl.service.DDDslTransientValueService;
import org.palladiosimulator.dataflow.dictionary.characterized.dsl.converter.CharacterizedDataDictionaryValueConverter;
import org.palladiosimulator.dataflow.dictionary.characterized.dsl.service.CharacterizedDataDictionaryDerivedStateComputer;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension
 * registry.
 */
public class DDDslRuntimeModule extends AbstractDDDslRuntimeModule {

    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return CharacterizedDataDictionaryValueConverter.class;
    }

    public Class<? extends IDerivedStateComputer> bindIDerivedStateComputer() {
        return CharacterizedDataDictionaryDerivedStateComputer.class;
    }

    @Override
    public Class<? extends XtextResource> bindXtextResource() {
        return DerivedStateAwareResource.class;
    }

    public Class<? extends IResourceDescription.Manager> bindIResourceDescriptionManager() {
        return DerivedStateAwareResourceDescriptionManager.class;
    }

    @Override
    public Class<? extends ITransientValueService> bindITransientValueService() {
        return DDDslTransientValueService.class;
    }

}
