/*
 * generated by Xtext 2.24.0
 */
package org.palladiosimulator.dataflow.confidentiality.pcm.dddsl;

import org.eclipse.emf.ecore.EPackage;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DDDslStandaloneSetup extends DDDslStandaloneSetupGenerated {

    public static void doSetup() {
        new DDDslStandaloneSetup().createInjectorAndDoEMFRegistration();
    }

    @Override
    public void register(Injector injector) {
        super.register(injector);

        if (!EPackage.Registry.INSTANCE.containsKey(
                org.palladiosimulator.dataflow.confidentiality.pcm.model.confidentiality.ConfidentialityPackage.eNS_URI)) {
            EPackage.Registry.INSTANCE.put(
                    org.palladiosimulator.dataflow.confidentiality.pcm.model.confidentiality.ConfidentialityPackage.eNS_URI,
                    org.palladiosimulator.dataflow.confidentiality.pcm.model.confidentiality.ConfidentialityPackage.eINSTANCE);
        }

        if (!EPackage.Registry.INSTANCE.containsKey(de.uka.ipd.sdq.stoex.StoexPackage.eNS_URI)) {
            EPackage.Registry.INSTANCE.put(de.uka.ipd.sdq.stoex.StoexPackage.eNS_URI,
                    de.uka.ipd.sdq.stoex.StoexPackage.eINSTANCE);
        }
    }

}
